name: Android CI (secrets check)

on:
  push:
    branches: [ main ]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Actions secrets exist
        run: |
          missing=0
          for k in OPENWEATHER_API_KEY MAPS_API_KEY GEMINI_API_KEY; do
            if [ -z "${!k}" ]; then
              echo "::error::$k is missing"
              missing=1
            else
              echo "$k: OK"
            fi
          done
          exit $missing
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
